-- CreateTable
CREATE TABLE "Job" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Task" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "jobId" INTEGER NOT NULL,
    "sequence" INTEGER NOT NULL,
    "label" TEXT,
    "j1" REAL NOT NULL,
    "j2" REAL NOT NULL,
    "j3" REAL NOT NULL,
    "j4" REAL NOT NULL,
    "j5" REAL NOT NULL,
    "j6" REAL NOT NULL,
    "rail" REAL NOT NULL,
    "speed" INTEGER NOT NULL DEFAULT 50,
    "delay" INTEGER NOT NULL DEFAULT 0,
    "gripper" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Task_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
